Complete basically everything except carousel
FraserHacks/fraserhacks1-recap pull request #2
Opened 2020-09-02 16:22 UTC by RyanL123

2020-09-02 21:39 UTC, jhthenerd approved these changes
you could parameterize some shit but its not blocking and it seems to render fine. plus its just a one-pager that doesn't need to be maintained so I'll let it slide.

2020-09-02 21:39 UTC, jhthenerd commented on src/components/Footer.js
> +                <Text color="#BDBDBD" maxWidth="600px" mt="25px" mb="100px">
maybe parameterize the color? idk

2020-09-02 21:39 UTC, jhthenerd commented on src/components/SEO.js
> +        <meta property="og:image" content="/banner.png" />
wait does pulling it from assets not work?

2020-09-02 21:39 UTC, jhthenerd commented on src/components/Title.js
> +        <Heading color="#298DC3" size={IsMobile() ? "md" : "lg"}>
parameterize color? also why u no use breakpoints they're literally built into chakra

2020-09-02 21:39 UTC, jhthenerd commented on src/components/Video.js
> +        <Text color="#BDBDBD" marginTop="25px" maxWidth="600px">
parameterize color

2020-09-02 21:39 UTC, jhthenerd commented on src/components/Video.js
> +        <Text color="#BDBDBD" maxWidth="600px">
also parameterize this

2020-09-02 21:39 UTC, jhthenerd commented on src/pages/index.js
>          <Box background="#131D24">
params

2020-09-02 21:39 UTC, jhthenerd commented on src/util/mediaQuery.js
> +    const mobile = useMediaQuery({ query: "(max-width: 960px)" })
bruh just use breakpoints

2020-09-02 21:46 UTC, jhthenerd commented
@davidli3100 thoughts?

2020-09-02 22:34 UTC, RyanL123 commented on src/components/SEO.js
> +        <meta property="og:image" content="/banner.png" />
apparently it has to be in static but I'm pretty sure it has to be an actual URL, we'll see what happens when it's on netlify

2020-09-02 22:45 UTC, jhthenerd requested changes
Nevermind, SEO is dead.
Please implement [Gatsby Plugin React Helmet](https://www.gatsbyjs.com/plugins/gatsby-plugin-react-helmet/) and [Gatsby Plugin Manifest](https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/)

2020-09-04 16:38 UTC, davidli3100 commented
Looks good but the photo at the bottom is still blurry asf @RyanL123 consider redoing it?

2020-09-07 19:22 UTC, jhthenerd requested changes
Just fix the favicon implementation and we should be good

2020-09-07 19:22 UTC, jhthenerd commented on gatsby-config.js
> +            resolve: `gatsby-plugin-manifest`,
Fix your favicon stuff, remove the custom implementation you have rn and replace with the built-in favicon generation functionality

See: https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/#automatic-mode-configuration

2020-09-08 22:48 UTC, jhthenerd approved these changes
LGTM

2020-09-08 22:51 UTC, merged

2020-10-13 00:55 UTC, err53 commented on src/components/Slider.js
> +const Slider = () => {
Size images properly, there's no need for a slider to be 1000 px across. Maybe like a few hundred px max.